filmproject/authentication/urls.py
from . import views
from django.urls import path
app_name='authentication'


urlpatterns = [
    path('reg',views.reg,name='reg'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

filmproject/filmapp/urls.py
from django.urls import path
from . import views

app_name = 'filmapp'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/<int:id>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    path('add_product/', views.add_product, name='add_product'),
    path('/edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('/delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('/product/<int:product_id>/add_comment/', views.add_comment, name='add_comment'),
    path('/product/<int:product_id>/add_rating/', views.add_rating, name='add_rating'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),


    
]

filmproject/filmproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filmapp.urls')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('searchapp/', include('searchapp.urls', namespace='searchapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

filmproject/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'

urlpatterns=[
    path('SearchResult',views.SearchResult,name='SearchResult'),
]

filmproject/filmapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser

class User(models.Model):
    username=models.CharField(max_length=255)
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=255)
    def __str__(self):
        return '{}'.format(self.username)
    
    
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('filmapp:products_by_category', args=[self.slug, self.id])

    def __str__(self):
        return '{}'.format(self.name)
    
class products(models.Model):
    name=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique=True)
    poster=models.ImageField(upload_to='poster',blank=True)
    description=models.TextField()
    release_date=models.DateField()
    actors=models.CharField(max_length=255)
    category_id=models.ForeignKey(category,on_delete=models.CASCADE)
    trailer_link=models.URLField()
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE, default=None)
    
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)
    
    def get_url(self):
        return reverse('filmapp:prodCatdetail',args=[self.category_id.slug,self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        if not isinstance(self.user, get_user_model()):
            self.user = get_user_model().objects.get(username=self.user.username)

        super().save(*args, **kwargs)


    def average_rating(self):
        ratings = Rating.objects.filter(product=self)
        if ratings.exists():
            return sum(rating.rating for rating in ratings) / ratings.count()
        return 0
    def total_ratings(self):
        return Rating.objects.filter(product=self).count()


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Rating(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def str(self):
        return f"{self.user.username} - {self.product.name} - {self.rating}"

filmproject/templates/add_comment.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Add Comment</h2>
    <form method="post" action="{% url 'filmapp:add_comment' product_id=product.id %}" style="margin-left: 20px; color: ghostwhite; padding-bottom: 170px;">
    {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Submit</button>
        <button class="btn btn-dark"><a href="{% url 'filmapp:allProdCat' %}">Cancel</a></button>
    </form>
{% endblock %}

filmproject/templates/add_product.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
</head>
<body>
    <h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Add Movie</h2>
    <form method="post" enctype="multipart/form-data" style="color: ghostwhite; margin-left: 10px; padding-bottom: 20px;">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Add Movie</button>
        <a href="{% url 'filmapp:allProdCat' %}"></a>
    </form>
</body>
</html>
{% endblock %}

filmproject/templates/add_rating.html
{% extends 'base.html' %}
{% block content %}
  <h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Add Rating</h2>
  <form method="post" style="padding-bottom: 385px; color: ghostwhite; margin-left: 10px;" action="{% url 'filmapp:add_rating' product_id=product.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Submit Rating</button>

  </form>

{% endblock %}

filmproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc51e437b8.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div style="background-color:rgb(0, 0, 0);">
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

filmproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155 }}
   {% else %}
       welcome to store where you can experience different tastes....
   {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -  Borcelle
    {% else %}
         see our new collections - Borcelle
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
      <div style="margin-top: 60px;">
        <div class="row my_row_class">
            <div class="mx-auto">
            <p class="text-center custom_a" ><a href="{% url 'filmapp:allProdCat' %}" class="custom_a" style="color:black;">Our Movie collections</a> </p>
            </div>
        </div>
      </div>
      
      <div>
             <h1 class="text-center my_title" style="color: firebrick;"><b>{{category.name}}</b></h1>
             <p class="text-center">{{category.description}}</p>
      </div>
    {% else %}

      <div class="my_image_padding" style="margin-top: 60px;">
           <img src="{% static 'img/cinema1.jpg' %}" alt="our products" width="1300px" height="430px">
      </div>
      <br>
      <div>
         <h1 class="text-center my_title" style="color:ghostwhite; font-weight: lighter;">Our Movie Collections </h1>
         <p class="text-center" style="color: ghostwhite; padding-left: 130px; padding-right: 130px; font-family:monospace;">A movie or film is a type of visual art that uses images and sounds to tell stories or teach people something. Most people watch movies to entertain themselves or to have fun. Some movies can make people laugh, but other movies can make them cry, or make them feel afraid.</p>
      </div>
    {% endif %}
     <div class="containers">
      <div class="row mx_auto" style="padding: 50px;">
        {% for product in products %}
           <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
           <div class="card text-center"  style="min-width:18rem; border-radius: 5px; box-shadow: 0 0 15px rgb(167, 32, 32); margin-bottom: 20px;">
            {% if product.poster %}
    <a href="{{ product.get_url }}">
        <img class="card-img-top my_image" style="width:100%; height:500px; object-fit: cover;" src="{{ product.poster.url }}" alt="{{ product.name }}">
    </a>
{% else %}
    <p>No poster available</p>
{% endif %}
           <div class="card-body">
             <h4>{{product.name}}</h4>
             <p>{{product.category_id}}</p>
           </div>
           </div>
           </div>
           
           
           {% endfor %} 
          
      </div>
    </div>
      <div> 
           <div class="mx-auto">
              {% if products.paginator.num_pages > 1 %}
              <hr>
              <div class="text-center">
                  {% for pg in products.paginator.page_range %}
                  <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}" style="margin-bottom:50px">{{pg}}</a>
                  {% endfor %}
              </div>
              {% endif %}
          </div> 
           <br>
      </div>
      
{% endblock %}  

filmproject/templates/delete_product.html
{% extends 'base.html' %}
{% block content %}
  <h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Confirm Delete</h2>
  <p style="color: ghostwhite; margin-left: 10px;">Are you sure you want to delete the product '{{ product.name }}'? This action cannot be undone.</p>

  <form method="post" style="color: ghostwhite; padding-bottom: 385px; margin-left: 10px;">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Yes, Delete</button>
    <a class="btn btn-dark" href="{% url 'filmapp:allProdCat' %}">Cancel</a>
  </form>
{% endblock %}

filmproject/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
  <h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Edit Product</h2>
  <form method="post" enctype="multipart/form-data" style="color: ghostwhite; padding-bottom: 30px; padding-left: 10px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Save Changes</button>
    <a class="btn btn-dark" href="{% url 'filmapp:allProdCat' %}">Cancel</a>
  </form>
{% endblock %}

filmproject/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<h2 style="color:rgb(185, 67, 67); font-weight: lighter; margin-left: 10px; margin-top: 60px;">Edit Profile</h2>
<form method="post" action="{% url 'filmapp:edit_profile'  %}" style="margin-left: 10px; color: ghostwhite; padding-bottom: 250px;">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-secondary" type="button" onclick=window.location.href='{% url 'filmapp:allProdCat' %}'>Save Changes</button>
  <button class="btn btn-success" type="submit">Save</button>
</form>
{% endblock %}

filmproject/templates/footer.html
<div class=" my_footer " style="background-color: lightgrey; height: 110px;">
    <div class="footer_p" >
      <p style="font-family:cursive; font-size: large; color: firebrick;">&copy; av cinema pvt ltd</p>
    </div>
       <div class="myFootericons" >
        <ul>
          <li class="list-inline-item">
            <a href="#"><i class="fa fa-facebook" style="color: #000000;"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="#"><i class="fa fa-twitter" style="color: #000000;"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="#"><i class="fa fa-linkedin" style="color: #000000;"></i></a>
          </li>
          <li class="list-inline-item">
            <a href="#"><i class="fa fa-instagram" style="color: #000000;"></i></a>
          </li>
        </ul>
  
       </div>              
  </div>

filmproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>Login</h2>
        <form action="{% url 'authentication:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Enter your username"><br>
            <input type="password" name="password" placeholder="Enter your password"><br>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

filmproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" style="background-color:lightgrey;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/" style="color:firebrick; font-family:cursive;">AV CINEMA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item" style="margin-top: 4px;">
            <a class="nav-link active" style="color: black;" aria-current="page" href="/">Home</a>
          </li>

          <li class="nav-item" style="margin-top: 4px;">
            <a class="nav-link" style="color: black;" href="#">Reviews</a>
          </li>
         
          <li class="nav-item dropdown {% if 'filmapp' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" style="margin-top: 4px; color: black;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Movie
            </a>
            <ul class="dropdown-menu" style="background-color: lightgrey;">
              <li><a class="dropdown-item" href="{% url 'filmapp:allProdCat' %}">All Movies</a></li>
              
              <li><hr class="dropdown-divider"></li>
          {% for cat in links %}
              <li><a class="dropdown-item" style="color: black;" href="{{cat.get_url}}">{{ cat.name }}</a></li>
            {% endfor %}

            <li><hr class="dropdown-divider"></li>
            {% if user.is_authenticated %}
                        <li><a class="dropdown-item" style="color: firebrick;" href="{% url 'filmapp:add_product' %}">Add Movie</a></li>
                    {% endif %}
            </ul>
          </li>

        <div class="ac" style="margin-left: 600px; margin-top: 5px; background-color: lightgrey;">
        <li class="nav-item dropdown {% if 'filmapp' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" style="color: black;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
        <ul class="dropdown-menu" style="background-color: lightgrey;">
          {% if user.is_authenticated %}
                    <span class="dropdown-item" style="text-transform:none;">Hello {{ user.username }}</span>
                    <li>
                      {% if user.is_authenticated %}
                        <a class="dropdown-item" style="text-transform:none;" href="{% url 'filmapp:edit_profile' %}">Edit Profile</a>
                        {% endif %}
                      </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" style="color: firebrick;" href="{% url 'authentication:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" style="color: black;" href="{% url 'authentication:reg' %}">Register</a></li>
            <li><a class="dropdown-item" style="color: black;" href="{% url 'authentication:login' %}">Login</a></li>
            {% endif %}
          </ul>
          </li>
          {% if user.is_authenticated %}
          {% endif %}
        </div>
        <br>
        <li>
            <a class="dropdown-item" style="margin-top: 4px; font-size: x-large;" href="#"><i class="fa-regular fa-heart"></i></a>
          </li>
          </ul>

          <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get" style="padding: 5px; border-radius: 10px;">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search" style="background-color: ghostwhite; color: rgb(0, 0, 0); border-color: #000000;" autocomplete="off">
            <button class="btn btn-outline-dark" type="submit" style="background-color: None"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>
    </div>
  </nav>

filmproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -  AV cinema

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class" style="margin-top: 60px;">
  <div class="mx-auto">
    <p style="margin-left:180px; color: ghostwhite; margin-left: 270px; margin-top: 10px;"><a href="{% url 'filmapp:allProdCat' %}" style="color: ghostwhite;">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
  </div>
    <div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.poster.url}}" alt="{{product.name}}" style="width: 400px; height: 500px; margin-bottom: 50px; border-radius: 10px; box-shadow: 0 0 10px rgb(245, 245, 245);">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6" style="color: ghostwhite;" >
            <div style="flex: 0 0 48%; color:white;" >
                <h1 style="margin-top: 0; color: #DE3163;">{{ product.name }}</h1>
                <p>{{ product.category_id }}</p>
                <p>Actors: {{ product.actors }}</p>
                <p>{{ product.description }}</p>
                <p>Release Date : {{ product.release_date }}</p>
                <p><a class="btn btn-dark" href="{{ product.trailer_link }}" style="text-decoration: none; color: white;">Watch the Trailer</a></p>

                {% if user == product.user %}
                <a class="btn btn-success" href="{% url 'filmapp:edit_product' id=product.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'filmapp:delete_product' id=product.id %}">Delete</a>
                {% endif %}
                  
                {% if user.is_authenticated %} <br><br>
                <h3>Comments</h3>
                <button type="button" style="color: black;" class="btn btn-secondary" onclick=window.location.href='{% url 'filmapp:add_comment' product_id=product.id %}'>Add Comment</button>
                <br>
                {% endif %}
                 {% for comment in product.comment_set.all %}
                <p>{{ comment.text }} - {{ comment.user.username }} at {{ comment.created_at }}</p>
                {% endfor %}

                {% if user.is_authenticated %}  
                <h2>Ratings</h2>
                <button type="button" style="color: black;" class="btn btn-secondary" onclick=window.location.href='{% url 'filmapp:add_rating' product_id=product.id %}'>Add Rating</button>
                <br>
                <p>Average Rating: {{ product.average_rating }}</p>
                <p>Total Ratings: {{ product.total_ratings }}</p>
                {% endif %}   


           </div>
    </div>
</div>
        {% endblock %}
    </div>
</div> 

filmproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }
         

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    
    <form action="{% url 'authentication:reg' %}" method="post">
        {% csrf_token %}
        <h2> <center>REGISTRATION</center></h2>
        <input type="text" name="username" placeholder="Enter your username"><br>
        <input type="text" name="first_name" placeholder="Enter your first name"><br>
        <input type="text" name="last_name" placeholder="Enter your last name"><br>
        <input type="email" name="email" placeholder="Enter your email"><br>
        <input type="password" name="password" placeholder="Enter your password"><br>
        <input type="password" name="password1" placeholder="Enter your confirm password"><br>

        <button type="submit" class="btn btn-dark">Register</button>
    </form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

filmproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     we have variety of products.
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text" style="color:ghostwhite">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="row mx_auto">
        {% for products in product %}
           <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
           <div class="card text-center"  style="width:300px;height:350px; box-shadow: 0 0 10px rgba(186, 24, 24, 0.838);">
             <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.poster.url}}" style="width:300px;height:350px;filter: brightness(70%);" alt="{{products.name}}"></a>
           <div class="card-body">

           </div>
           </div>
           </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text" style="padding-bottom: 20px;"> 0 results found</p>
</div>
{% endfor %}
</div>
{% endblock %}